# tor.sh — slate-controller Tor subsystem handler (rewritten 2026-05-31).
#
# Reads two slices of the profile JSON :
#   1. @.tor (global) :
#        { enabled, use_bridges, bridges:[...],
#          socks_port, control_port, trans_port, dns_port }
#      The "enabled" bit is the global daemon master switch (= the value
#      of /api/tor/settings.daemon_enabled in the controller DB).
#
#   2. @.network.items[*] (per-network) :
#        { slug, bridge_name, gateway_ip,
#          tor_route_mode (off|transparent|socks_only),
#          tor_dns_over_tor (bool),
#          tor_kill_switch (bool) }
#      These come from /api/networks/<slug> and drive the per-bridge
#      iptables routing : a `transparent` network has its TCP redirected
#      to Tor's TransPort ; DNS-over-Tor adds a UDP/53→DNSPort redirect ;
#      kill-switch adds a defensive FORWARD DROP for anything that isn't
#      a localhost redirect (catches ICMP / raw IP leaks if Tor isn't
#      catching everything).
#
# Apply model :
#   - Always clean the rules we own first (idempotent).
#   - If Tor shouldn't run → stop daemon, leave rules cleaned.
#   - Else → write /etc/tor/torrc, restart daemon if torrc changed,
#     install per-network iptables rules.
#
# `tor` is not part of the stock GL.iNet firmware ; if the binary is
# missing we log a clear "not installed" line rather than failing the
# whole apply. Use POST /api/tor/install to opkg-install it.

_TOR_TORRC=/etc/tor/torrc
_TOR_TORRC_BACKUP=/etc/tor/torrc.gl-orig
_TOR_INIT=/etc/init.d/tor
_TOR_NAT_CHAIN=SC_TOR_NAT          # our nat chain (PREROUTING jump)
_TOR_KILL_CHAIN=SC_TOR_KILL        # our filter chain (FORWARD jump)
_TOR_MANAGED_MARK="# Generated by slate-controller tor.sh"

_tor_field() { echo "$1" | jsonfilter -e "$2" 2>/dev/null; }

# Stake an exclusive claim over /etc/tor/torrc + the daemon lifecycle :
#
#   - tor.global.manual=1   tells gl-sdk4-ui-torview "the user manages
#                           torrc manually" → its toggle stops
#                           regenerating /etc/tor/torrc.
#   - tor.global.enable=1   the GL.iNet init.d/tor refuses to start
#                           procd-side when this is 0. Lifting it to 1
#                           lets us drive start/stop normally. Cosmetic
#                           side effect : the GL.iNet UI shows "Tor ON"
#                           even when we keep the daemon stopped — the
#                           authoritative state is the daemon process,
#                           not their checkbox.
#   - first-apply backup    preserves the firmware-default torrc to
#                           /etc/tor/torrc.gl-orig so the operator can
#                           restore if they want to abandon slate-ctrl.
_tor_claim_ownership() {
  uci -q get tor.global >/dev/null 2>&1 || return 0
  local cur_manual cur_enable
  cur_manual=$(uci -q get tor.global.manual 2>/dev/null)
  cur_enable=$(uci -q get tor.global.enable 2>/dev/null)
  local changed=0
  if [ "$cur_manual" != "1" ]; then
    uci set tor.global.manual=1
    changed=1
  fi
  if [ "$cur_enable" != "1" ]; then
    uci set tor.global.enable=1
    changed=1
  fi
  [ "$changed" = "1" ] && uci commit tor 2>/dev/null
  # First-time backup of the firmware torrc — only do it if our marker
  # isn't already in there (idempotent).
  if [ -f "$_TOR_TORRC" ] && [ ! -f "$_TOR_TORRC_BACKUP" ]; then
    if ! grep -q "$_TOR_MANAGED_MARK" "$_TOR_TORRC" 2>/dev/null; then
      cp "$_TOR_TORRC" "$_TOR_TORRC_BACKUP" 2>/dev/null
      chmod 644 "$_TOR_TORRC_BACKUP" 2>/dev/null
      echo "tor: backed up GL.iNet stock torrc to $_TOR_TORRC_BACKUP"
    fi
  fi
}

# Strip our marker chains from the live tables. Safe to call even on a
# clean system (every command silenced).
_tor_clean_rules() {
  iptables -t nat -D PREROUTING -j $_TOR_NAT_CHAIN 2>/dev/null
  iptables -t nat -F $_TOR_NAT_CHAIN 2>/dev/null
  iptables -t nat -X $_TOR_NAT_CHAIN 2>/dev/null
  iptables -D FORWARD -j $_TOR_KILL_CHAIN 2>/dev/null
  iptables -F $_TOR_KILL_CHAIN 2>/dev/null
  iptables -X $_TOR_KILL_CHAIN 2>/dev/null
  _tor_clean_ipv6_drops
}

# Write torrc and return 0 if content changed (so the caller restarts the
# daemon), 1 otherwise.
#
# SECURITY MODEL : SOCKS / TransPort / DNSPort bind PER-GATEWAY (one line
# per Tor-eligible bridge), never 0.0.0.0 — only clients of the bridge
# can reach their own gateway, so other LAN segments and any WAN ingress
# can't pivot through our Tor daemon as a free anonymising proxy.
# ControlPort stays on 127.0.0.1 with cookie auth (loopback only).
#
# $1 socks_port  $2 ctrl_port  $3 trans_port  $4 dns_port
# $5 use_bridges  $6 payload (@.tor slice)  $7 exit_cc
# $8 trans_gws    newline-separated gateways needing TransPort+DNSPort
# $9 socks_gws    newline-separated gateways needing SocksPort
_tor_write_torrc() {
  local sp="$1" cp="$2" tp="$3" dp="$4" use_br="$5"
  local payload="$6" exit_cc="$7"
  local trans_gws="$8" socks_gws="$9"
  mkdir -p /etc/tor /var/lib/tor /var/log/tor
  local tmp=/tmp/.slate_ctrl_torrc.new
  # Locate a GeoIP file — tor-geoipdb installs to /usr/share/tor/geoip,
  # and GL.iNet's firmware ships one in /rom/usr/share/tor/geoip.
  local geoip_path=""
  for cand in /usr/share/tor/geoip /rom/usr/share/tor/geoip; do
    if [ -f "$cand" ]; then geoip_path="$cand"; break; fi
  done
  local geoip6_path=""
  for cand in /usr/share/tor/geoip6 /rom/usr/share/tor/geoip6; do
    if [ -f "$cand" ]; then geoip6_path="$cand"; break; fi
  done
  {
    echo "$_TOR_MANAGED_MARK — DO NOT EDIT MANUALLY"
    echo "# (GL.iNet UI is locked out via uci tor.global.manual=1)"
    echo "User tor"
    echo "DataDirectory /var/lib/tor"
    echo "Log notice file /var/log/tor/notices.log"
    echo "ControlPort 127.0.0.1:$cp"
    echo "CookieAuthentication 1"
    [ -n "$geoip_path" ]  && echo "GeoIPFile $geoip_path"
    [ -n "$geoip6_path" ] && echo "GeoIPv6File $geoip6_path"
    if [ -n "$exit_cc" ]; then
      echo "ExitNodes {$exit_cc}"
      echo "StrictNodes 1"
    fi
    # SocksPort : one line per Tor-eligible bridge gateway. Fallback to
    # 127.0.0.1 ONLY when no bridge requested SOCKS (still useful for
    # ad-hoc tests on the device itself).
    if [ -n "$socks_gws" ]; then
      printf '%s\n' "$socks_gws" | while IFS= read -r g; do
        [ -n "$g" ] && echo "SocksPort ${g}:${sp} IsolateClientAddr IsolateDestAddr"
      done
    else
      echo "SocksPort 127.0.0.1:${sp}"
    fi
    # TransPort / DNSPort : per-gateway binding. iptables REDIRECT's
    # --to-port rewrites the destination to the incoming-iface address,
    # which matches the gateway Tor is listening on.
    if [ -n "$trans_gws" ]; then
      echo "AutomapHostsOnResolve 1"
      echo "VirtualAddrNetworkIPv4 10.192.0.0/10"
      printf '%s\n' "$trans_gws" | while IFS= read -r g; do
        [ -n "$g" ] && {
          echo "TransPort ${g}:${tp}"
          echo "DNSPort   ${g}:${dp}"
        }
      done
    fi
    if [ "$use_br" = "true" ]; then
      echo "UseBridges 1"
      if command -v obfs4proxy >/dev/null 2>&1; then
        echo "ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy"
      fi
      # payload is the @.tor slice, so bridges live at @.bridges[*].
      local n_br i_b line
      n_br=$(echo "$payload" | jsonfilter -e "@.bridges[*]" 2>/dev/null | wc -l)
      i_b=0
      while [ "$i_b" -lt "$n_br" ]; do
        line=$(echo "$payload" | jsonfilter -e "@.bridges[$i_b]" 2>/dev/null)
        [ -n "$line" ] && echo "Bridge $line"
        i_b=$((i_b + 1))
      done
    fi
  } > "$tmp"
  # Compare hashes; replace only if different so we don't churn the daemon.
  local new_hash old_hash
  new_hash=$(md5sum "$tmp" 2>/dev/null | awk '{print $1}')
  old_hash=$(md5sum "$_TOR_TORRC" 2>/dev/null | awk '{print $1}')
  if [ "$new_hash" != "$old_hash" ]; then
    mv "$tmp" "$_TOR_TORRC"
    chown tor:tor "$_TOR_TORRC" 2>/dev/null
    chown -R tor:tor /var/lib/tor /var/log/tor 2>/dev/null
    return 0   # changed
  fi
  rm -f "$tmp"
  return 1     # unchanged
}

# Install one transparent network's full kit of NAT + filter + IPv6 +
# kill-switch rules.  Inputs : bridge, gw, dns_tor, kill_sw, tp, dp.
_tor_install_net_rules() {
  local bridge="$1" gw="$2" dns_tor="$3" kill_sw="$4" tp="$5" dp="$6"
  [ -z "$bridge" ] && return 0

  # Exempt the gateway IP — SSH / LuCI / AdGuard must stay reachable on
  # the local LAN without going through Tor.
  if [ -n "$gw" ]; then
    iptables -t nat -A $_TOR_NAT_CHAIN -i "$bridge" -d "$gw"/32 -j RETURN
  fi

  # Redirect every TCP SYN to Tor's TransPort.
  iptables -t nat -A $_TOR_NAT_CHAIN -i "$bridge" -p tcp --syn -j REDIRECT --to-port "$tp"

  # DNS over Tor (UDP + TCP/53).
  if [ "$dns_tor" = "true" ]; then
    iptables -t nat -A $_TOR_NAT_CHAIN -i "$bridge" -p udp --dport 53 -j REDIRECT --to-port "$dp"
    iptables -t nat -A $_TOR_NAT_CHAIN -i "$bridge" -p tcp --dport 53 -j REDIRECT --to-port "$dp"
  fi

  # ANTI-IPv6-LEAK : Tor only proxies IPv4. Without this, any AAAA-
  # resolved destination, ICMPv6, or v6 fallback sends the public IPv6
  # of the client over WAN in clear. We block IPv6 forward on the
  # bridge regardless of the kill_switch flag — it's never the right
  # behaviour to let IPv6 leak when transparent routing is on.
  if command -v ip6tables >/dev/null 2>&1; then
    ip6tables -I FORWARD -i "$bridge" -j DROP 2>/dev/null
  fi

  # Kill-switch (filter table) : DROP every IPv4 packet from this
  # bridge whose destination isn't localhost (where Tor catches it).
  # Catches UDP / ICMP / raw IP / any protocol Tor can't proxy.
  if [ "$kill_sw" = "true" ]; then
    iptables -A $_TOR_KILL_CHAIN -i "$bridge" ! -d 127.0.0.0/8 -j DROP
  fi
}

# Drop the ip6tables FORWARD DROP rule we installed when transparent
# routing was on. Called by _tor_clean_rules for idempotency.
_tor_clean_ipv6_drops() {
  command -v ip6tables >/dev/null 2>&1 || return 0
  # We don't know which bridges had rules — flush is too broad — so we
  # iterate active bridges and pull a single -D for each matching rule.
  local br
  for br in $(bridge link 2>/dev/null | grep -oE 'master br-[a-z0-9_-]+' | awk '{print $2}' | sort -u); do
    while ip6tables -C FORWARD -i "$br" -j DROP 2>/dev/null; do
      ip6tables -D FORWARD -i "$br" -j DROP 2>/dev/null
    done
  done
}

# Flush conntrack so any pre-existing connections from a now-transparent
# bridge get re-routed via Tor instead of bypassing it. Without this,
# the long-lived TCP connections (XMPP, IMAP idle, RDP, SSH) the user
# already has open continue to leak past the redirect.
_tor_flush_conntrack() {
  if command -v conntrack >/dev/null 2>&1; then
    conntrack -F >/dev/null 2>&1
  elif [ -w /proc/sys/net/netfilter/nf_conntrack_flush ] 2>/dev/null; then
    echo 1 > /proc/sys/net/netfilter/nf_conntrack_flush 2>/dev/null
  fi
}

tor_apply() {
  local payload
  payload=$(cat)
  if [ -z "$payload" ] || [ "$payload" = "null" ]; then
    return 0
  fi

  # Tor binary presence — clean any leftover rules and bail gracefully
  # so the apply doesn't fail just because the user hasn't hit "install"
  # yet. The controller surfaces install=false in /api/tor/status.
  if ! command -v tor >/dev/null 2>&1; then
    _tor_clean_rules
    [ -x "$_TOR_INIT" ] && $_TOR_INIT stop >/dev/null 2>&1
    echo "tor: binary not installed — skip (POST /api/tor/install to add)"
    return 0
  fi

  # Claim exclusive ownership of /etc/tor/torrc + the daemon. After this
  # the GL.iNet UI tor toggle is a no-op (manual=1, enable=0) and our
  # subsequent torrc writes won't be clobbered by gl-sdk4-ui-torview.
  _tor_claim_ownership

  # slate-ctrl pipes only the @.tor slice into stdin — so queries against
  # $payload use @.<field>, not @.tor.<field>. The per-network routing
  # block lives at @.network.items in the FULL profile JSON ; we re-read
  # that file via the path slate-ctrl exports as SLATE_CTRL_PROFILE_NAME.
  local enabled use_bridges trans_port dns_port socks_port control_port exit_cc
  enabled=$(_tor_field "$payload" "@.enabled")
  use_bridges=$(_tor_field "$payload" "@.use_bridges")
  trans_port=$(_tor_field "$payload" "@.trans_port")
  dns_port=$(_tor_field "$payload" "@.dns_port")
  socks_port=$(_tor_field "$payload" "@.socks_port")
  control_port=$(_tor_field "$payload" "@.control_port")
  exit_cc=$(_tor_field "$payload" "@.exit_country_code")
  [ -z "$trans_port" ]   && trans_port=9040
  [ -z "$dns_port" ]     && dns_port=5353
  [ -z "$socks_port" ]   && socks_port=9050
  [ -z "$control_port" ] && control_port=9051

  # Full profile JSON path — required for the per-network discovery
  # below. SLATE_CTRL_PROFILE_NAME is exported by slate-ctrl cmd_apply.
  local full_json=""
  if [ -n "${SLATE_CTRL_PROFILE_NAME:-}" ]; then
    full_json="/etc/slate-controller/profiles/${SLATE_CTRL_PROFILE_NAME}.json"
    [ -f "$full_json" ] || full_json=""
  fi

  # Discover the per-network routing layer from the full profile JSON.
  # Build :
  #   - trans_nets   "bridge:gw:dns_tor:kill_sw\n..."   (transparent only)
  #   - trans_gws    "gw\n..."   (transparent only, for torrc Trans/DNS bind)
  #   - socks_gws    "gw\n..."   (transparent OR socks_only, for SocksPort)
  local n_count needs_transparent=0 trans_nets="" trans_gws="" socks_gws="" i=0
  if [ -n "$full_json" ]; then
    n_count=$(jsonfilter -i "$full_json" -e "@.network.items[*].slug" 2>/dev/null | wc -l)
    while [ "$i" -lt "$n_count" ]; do
      local mode bridge gw dns_tor kill_sw
      mode=$(jsonfilter -i "$full_json" -e "@.network.items[$i].tor_route_mode" 2>/dev/null)
      bridge=$(jsonfilter -i "$full_json" -e "@.network.items[$i].bridge_name" 2>/dev/null)
      gw=$(jsonfilter -i "$full_json" -e "@.network.items[$i].gateway_ip" 2>/dev/null)
      dns_tor=$(jsonfilter -i "$full_json" -e "@.network.items[$i].tor_dns_over_tor" 2>/dev/null)
      kill_sw=$(jsonfilter -i "$full_json" -e "@.network.items[$i].tor_kill_switch" 2>/dev/null)
      if [ "$mode" = "transparent" ] && [ -n "$bridge" ]; then
        needs_transparent=1
        trans_nets="${trans_nets}${bridge}:${gw}:${dns_tor}:${kill_sw}
"
        [ -n "$gw" ] && {
          trans_gws="${trans_gws}${gw}
"
          socks_gws="${socks_gws}${gw}
"
        }
      elif [ "$mode" = "socks_only" ] && [ -n "$gw" ]; then
        socks_gws="${socks_gws}${gw}
"
      fi
      i=$((i + 1))
    done
  fi

  # Always start by clearing our own rules — both branches (stop vs run)
  # converge through this state.
  _tor_clean_rules

  # Daemon decision : only run when the global switch is on. The
  # per-network transparent layer is only meaningful with the daemon
  # running, but conversely the user might want Tor on for SOCKS even
  # without any transparent network.
  if [ "$enabled" != "true" ]; then
    if [ -x "$_TOR_INIT" ]; then
      $_TOR_INIT stop >/dev/null 2>&1
      $_TOR_INIT disable >/dev/null 2>&1
    fi
    echo "tor: daemon_enabled=false — stopped"
    return 0
  fi

  # Write torrc + restart only if it changed. We now pass the per-bridge
  # gateway lists so the daemon binds SOCKS / Trans / DNS to those IPs
  # only — never 0.0.0.0.
  if _tor_write_torrc "$socks_port" "$control_port" "$trans_port" \
                       "$dns_port" "$use_bridges" \
                       "$payload" "$exit_cc" \
                       "$trans_gws" "$socks_gws"; then
    echo "tor: torrc updated — restart"
    $_TOR_INIT enable >/dev/null 2>&1
    $_TOR_INIT restart >/dev/null 2>&1
  else
    # Daemon may be down even if torrc didn't change (first apply after
    # a reboot, or operator stopped it manually).
    $_TOR_INIT enable >/dev/null 2>&1
    $_TOR_INIT start >/dev/null 2>&1
  fi

  # Install NAT redirects for transparent networks + kill-switch rules.
  if [ "$needs_transparent" = "1" ]; then
    iptables -t nat -N $_TOR_NAT_CHAIN 2>/dev/null
    iptables -t nat -I PREROUTING -j $_TOR_NAT_CHAIN
    iptables -N $_TOR_KILL_CHAIN 2>/dev/null
    iptables -I FORWARD -j $_TOR_KILL_CHAIN

    local entry oldifs="$IFS"
    IFS='
'
    for entry in $trans_nets; do
      [ -z "$entry" ] && continue
      local br_part gw_part dns_part kill_part
      br_part="${entry%%:*}"
      local r1="${entry#*:}"
      gw_part="${r1%%:*}"
      local r2="${r1#*:}"
      dns_part="${r2%%:*}"
      kill_part="${r2#*:}"
      IFS="$oldifs"
      _tor_install_net_rules "$br_part" "$gw_part" "$dns_part" "$kill_part" \
                              "$trans_port" "$dns_port"
      IFS='
'
    done
    IFS="$oldifs"

    local n_trans
    n_trans=$(printf '%s' "$trans_nets" | grep -c .)
    echo "tor: $n_trans network(s) routed transparently"

    # Flush conntrack so already-established TCP / UDP connections from
    # tor-routed bridges get re-routed via Tor instead of continuing to
    # leak past the redirect until they close.
    _tor_flush_conntrack
    echo "tor: conntrack flushed (anti-orphan)"
  else
    echo "tor: daemon up, no transparent network — SOCKS only on :$socks_port"
  fi
}
