"""add devices + device_secrets

Revision ID: 08d38c7b0ee4
Revises: 5a25e3e7439a
Create Date: 2026-05-21 13:00:07.154695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d38c7b0ee4'
down_revision: Union[str, Sequence[str], None] = '5a25e3e7439a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('host', sa.String(length=120), nullable=False),
    sa.Column('rpc_port', sa.Integer(), nullable=False),
    sa.Column('rpc_scheme', sa.String(length=8), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('tls_fingerprint_sha256', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=False),
    sa.Column('last_probe_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adopted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_devices_slug')
    )
    op.create_table('device_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('encrypted_value', sa.LargeBinary(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'kind', name='uq_device_secrets_kind')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_secrets')
    op.drop_table('devices')
    # ### end Alembic commands ###
