"""add app_secrets

Revision ID: 5a25e3e7439a
Revises: ddde6f23c5d8
Create Date: 2026-05-21 11:50:31.466280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a25e3e7439a'
down_revision: Union[str, Sequence[str], None] = 'ddde6f23c5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_secrets',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('encrypted_value', sa.LargeBinary(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_secrets')
    # ### end Alembic commands ###
