"""initial schema

Revision ID: ddde6f23c5d8
Revises: 
Create Date: 2026-05-21 09:40:15.584544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddde6f23c5d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('bridge_name', sa.String(length=32), nullable=False),
    sa.Column('subnet_cidr', sa.String(length=32), nullable=False),
    sa.Column('gateway_ip', sa.String(length=40), nullable=False),
    sa.Column('dhcp_enabled', sa.Boolean(), nullable=False),
    sa.Column('isolated_from_lan', sa.Boolean(), nullable=False),
    sa.Column('vlan_tag', sa.Integer(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=False),
    sa.Column('ipv6_enabled', sa.Boolean(), nullable=False),
    sa.Column('ipv6_subnet_cidr', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_networks_slug')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_profiles_name')
    )
    op.create_table('vpn_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('interface_address', sa.String(length=128), nullable=False),
    sa.Column('dns_servers', sa.String(length=256), nullable=False),
    sa.Column('peer_public_key', sa.String(length=64), nullable=False),
    sa.Column('peer_endpoint', sa.String(length=128), nullable=False),
    sa.Column('peer_allowed_ips', sa.String(length=256), nullable=False),
    sa.Column('private_key_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_vpn_configs_name')
    )
    op.create_table('wifi_ssids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('ssid_name', sa.String(length=32), nullable=False),
    sa.Column('band', sa.String(length=8), nullable=False),
    sa.Column('security', sa.String(length=16), nullable=False),
    sa.Column('password_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('network_slug', sa.String(length=64), nullable=False),
    sa.Column('client_isolation', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_wifi_ssids_slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wifi_ssids')
    op.drop_table('vpn_configs')
    op.drop_table('profiles')
    op.drop_table('networks')
    op.drop_table('app_state')
    # ### end Alembic commands ###
