import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  CheckCircle2,
  Clock,
  Eye,
  EyeOff,
  Globe,
  Lock,
  LogIn,
  LogOut,
  Power,
  RefreshCw,
  Settings,
  Terminal,
  User,
} from "lucide-react";
import { Link } from "react-router-dom";
import {
  connectFortinet,
  disconnectFortinet,
  getFortinetLogs,
  getFortinetStatus,
  listFortinetConfigs,
} from "@/api/fortinet";
import type {
  FortinetConfigPublic,
  FortinetState,
} from "@/types/fortinet";
import { cn } from "@/lib/utils";
import { errorMessage } from "@/lib/error-utils";

// ──────────────────────────── helpers ─────────────────────────────────

const STATE_CHIP: Record<FortinetState, string> = {
  unknown: "",
  connecting: "cyber-chip-warn",
  up: "cyber-chip-ok",
  disconnecting: "cyber-chip-warn",
  down: "",
  failed: "cyber-chip-on",
};

const STATE_LABEL: Record<FortinetState, string> = {
  unknown: "inconnu",
  connecting: "connexion…",
  up: "UP",
  disconnecting: "déconnexion…",
  down: "déconnecté",
  failed: "échec",
};

function fmtBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  if (n < 1024 * 1024 * 1024) return `${(n / 1024 / 1024).toFixed(1)} MB`;
  return `${(n / 1024 / 1024 / 1024).toFixed(2)} GB`;
}

function fmtUptime(s: number): string {
  if (s < 60) return `${s}s`;
  const m = Math.floor(s / 60);
  const sec = s % 60;
  if (m < 60) return `${m}m${sec}s`;
  const h = Math.floor(m / 60);
  const mm = m % 60;
  return `${h}h${mm}m`;
}

// ──────────────────────────── login form (when DOWN) ──────────────────

function LoginForm({
  configs,
  onLoggedIn,
}: {
  configs: FortinetConfigPublic[];
  onLoggedIn: () => void;
}) {
  const [selectedSlug, setSelectedSlug] = useState<string>(
    configs[0]?.slug ?? "",
  );
  const selected = configs.find((c) => c.slug === selectedSlug);
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [showPw, setShowPw] = useState(false);

  // Note : the password field accepts the TOTP / 2FA code generated by
  // the authenticator app — most Fortinet deployments expect the
  // password to be the time-based one-time code (not a separate OTP
  // prompt). The backend can also receive a distinct ``otp`` value for
  // gateways that require both ; this form keeps it simple and folds
  // the TOTP into the password.

  // Reset typed username when switching configs in the dropdown — keep
  // creds out of memory across selections.
  function pickConfig(slug: string) {
    setSelectedSlug(slug);
    setUsername("");
    setPassword("");
  }

  const connect = useMutation({
    mutationFn: () =>
      connectFortinet(selectedSlug, "", {
        username,
        password,
      }),
    onSuccess: () => {
      // Wipe credentials from memory the moment the tunnel comes up.
      setPassword("");
      setUsername("");
      onLoggedIn();
    },
  });

  function onSubmit(e: FormEvent) {
    e.preventDefault();
    connect.mutate();
  }

  if (configs.length === 0) {
    return (
      <article className="cyber-card p-6">
        <p className="text-sm text-[color:var(--color-cyber-muted)]">
          Aucune configuration Fortinet enregistrée. En créer une depuis{" "}
          <Link
            to="/vpn/fortinet"
            className="cyber-glow underline"
          >
            VPN → Fortinet
          </Link>{" "}
          au préalable.
        </p>
      </article>
    );
  }

  return (
    <form onSubmit={onSubmit} className="cyber-card cyber-card-accent p-5 sm:p-6">
      <header className="mb-4 flex items-center gap-2">
        <LogIn className="cyber-glow h-4 w-4" />
        <h2 className="cyber-display cyber-glow text-base sm:text-lg">
          SE CONNECTER
        </h2>
      </header>

      <div className="space-y-4">
        {configs.length > 1 && (
          <label className="block">
            <span className="cyber-label mb-1.5 block">gateway</span>
            <select
              value={selectedSlug}
              onChange={(e) => pickConfig(e.target.value)}
              className="cyber-input w-full px-3 py-3 text-base"
            >
              {configs.map((c) => (
                <option key={c.slug} value={c.slug}>
                  {c.display_name || c.slug} · {c.gateway_host}
                </option>
              ))}
            </select>
          </label>
        )}

        {selected && (
          <div className="cyber-hatch border-y border-[color:var(--color-cyber-border)] px-3 py-2 text-[11px]">
            <div className="flex items-center gap-2">
              <Globe className="h-3 w-3 text-[color:var(--color-cyber-accent)]" />
              <span className="font-mono">
                {selected.gateway_host}:{selected.gateway_port}
              </span>
            </div>
          </div>
        )}

        <label className="block">
          <span className="cyber-label mb-1.5 flex items-center gap-1.5">
            <User className="h-3 w-3" />
            username
          </span>
          <input
            type="text"
            required
            autoComplete="username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            className="cyber-input w-full px-4 py-3 text-base font-mono"
          />
        </label>

        <label className="block">
          <span className="cyber-label mb-1.5 flex items-center gap-1.5">
            <Lock className="h-3 w-3" />
            password
          </span>
          <div className="relative">
            <input
              type={showPw ? "text" : "password"}
              required
              autoComplete="one-time-code"
              inputMode="numeric"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="cyber-input w-full py-3 pl-4 pr-12 text-base font-mono tracking-[0.2em]"
              placeholder="code 2FA"
            />
            <button
              type="button"
              onClick={() => setShowPw((v) => !v)}
              className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-[color:var(--color-cyber-muted)] hover:text-[color:var(--color-cyber-accent)]"
            >
              {showPw ? (
                <EyeOff className="h-4 w-4" />
              ) : (
                <Eye className="h-4 w-4" />
              )}
            </button>
          </div>
          <span className="mt-1 block text-[10px] uppercase tracking-[0.15em] text-[color:var(--color-cyber-dim)]">
            ▸ code TOTP de l'application 2FA · jamais stocké au repos
          </span>
        </label>

        <button
          type="submit"
          disabled={
            connect.isPending || !username || !password || !selectedSlug
          }
          className="cyber-button flex w-full items-center justify-center gap-2 px-4 py-4 text-sm disabled:opacity-50"
        >
          <Power className="h-4 w-4" />
          {connect.isPending ? "connexion…" : "Se connecter"}
        </button>

        {connect.error && (
          <p className="cyber-chip cyber-chip-on block !rounded-none px-3 py-2 text-xs">
            {errorMessage(connect.error)}
          </p>
        )}

        <p className="text-center text-[10px] italic text-[color:var(--color-cyber-dim)]">
          Le tunnel monte en 5-25 s · jusqu'à 60 s si push 2FA
        </p>
      </div>
    </form>
  );
}

// ──────────────────────────── status panel (when UP) ──────────────────

function ConnectedPanel({
  config,
}: {
  config: FortinetConfigPublic | undefined;
}) {
  const queryClient = useQueryClient();
  const statusQ = useQuery({
    queryKey: ["forti", "status"],
    queryFn: getFortinetStatus,
    refetchInterval: 5_000,
  });
  const disc = useMutation({
    mutationFn: disconnectFortinet,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["forti"] });
    },
  });

  const st = statusQ.data;

  return (
    <article className="cyber-card cyber-card-accent p-5 sm:p-6">
      <header className="mb-3 flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <CheckCircle2 className="cyber-glow h-4 w-4 text-[color:var(--color-cyber-ok)]" />
          <h2 className="cyber-display cyber-glow text-base sm:text-lg">
            CONNECTÉ
          </h2>
        </div>
        {st && (
          <span className={cn("cyber-chip", STATE_CHIP[st.state])}>
            {STATE_LABEL[st.state]}
          </span>
        )}
      </header>

      {statusQ.isLoading && (
        <p className="text-xs text-[color:var(--color-cyber-muted)]">
          probe SSH…
        </p>
      )}
      {statusQ.error && (
        <p className="cyber-chip cyber-chip-on block !rounded-none px-3 py-2 text-xs">
          {errorMessage(statusQ.error)}
        </p>
      )}

      {st && (
        <dl className="grid grid-cols-1 gap-y-2 text-sm sm:grid-cols-[auto_1fr] sm:gap-x-4">
          {(config?.display_name || config?.slug) && (
            <>
              <dt className="cyber-label !text-[10px] flex items-center gap-1.5">
                <Globe className="h-3 w-3" />
                gateway
              </dt>
              <dd className="break-all font-mono">
                {config.display_name || config.slug}
                <span className="ml-2 text-[10px] text-[color:var(--color-cyber-muted)]">
                  ({config.gateway_host}:{config.gateway_port})
                </span>
              </dd>
            </>
          )}
          {st.ppp_iface && (
            <>
              <dt className="cyber-label !text-[10px]">iface ppp</dt>
              <dd className="font-mono">{st.ppp_iface}</dd>
            </>
          )}
          {st.tunnel_ip && (
            <>
              <dt className="cyber-label !text-[10px]">IP tunnel</dt>
              <dd className="font-mono">{st.tunnel_ip}</dd>
            </>
          )}
          {st.gateway_ip && (
            <>
              <dt className="cyber-label !text-[10px]">peer</dt>
              <dd className="font-mono">{st.gateway_ip}</dd>
            </>
          )}
          <dt className="cyber-label !text-[10px] flex items-center gap-1.5">
            <Clock className="h-3 w-3" />
            uptime
          </dt>
          <dd className="font-mono">
            {st.uptime_seconds > 0 ? fmtUptime(st.uptime_seconds) : "—"}
          </dd>
          <dt className="cyber-label !text-[10px]">trafic</dt>
          <dd className="flex flex-wrap items-center gap-3 font-mono">
            <span className="inline-flex items-center gap-1">
              <ArrowDown className="h-3 w-3 text-[color:var(--color-cyber-ok)]" />
              {fmtBytes(st.rx_bytes)}
            </span>
            <span className="inline-flex items-center gap-1">
              <ArrowUp className="h-3 w-3 text-[color:var(--color-cyber-accent)]" />
              {fmtBytes(st.tx_bytes)}
            </span>
          </dd>
        </dl>
      )}

      <button
        type="button"
        disabled={disc.isPending}
        onClick={() => {
          if (
            confirm(
              "Déconnecter le tunnel Fortinet ?\n\nLes réseaux egress_via_forti tomberont sur leur kill-switch (drop ou WAN selon config par réseau).",
            )
          )
            disc.mutate();
        }}
        className="mt-4 flex w-full items-center justify-center gap-2 border border-[color:var(--color-cyber-warn)] bg-[color:var(--color-cyber-warn)]/8 px-4 py-4 text-sm uppercase tracking-[0.15em] text-[color:var(--color-cyber-warn)] hover:bg-[color:var(--color-cyber-warn)]/15 disabled:opacity-50"
      >
        <LogOut className="h-4 w-4" />
        {disc.isPending ? "déconnexion…" : "Se déconnecter"}
      </button>

      {disc.error && (
        <p className="mt-3 cyber-chip cyber-chip-on block !rounded-none px-3 py-2 text-xs">
          {errorMessage(disc.error)}
        </p>
      )}
    </article>
  );
}

// ──────────────────────────── logs viewer ─────────────────────────────

function LogsViewer() {
  const [open, setOpen] = useState(false);
  const q = useQuery({
    queryKey: ["forti", "logs"],
    queryFn: () => getFortinetLogs(200),
    enabled: open,
    refetchInterval: open ? 5_000 : false,
  });
  return (
    <details
      className="cyber-card p-3"
      open={open}
      onToggle={(e) => setOpen((e.target as HTMLDetailsElement).open)}
    >
      <summary className="cyber-label flex cursor-pointer items-center gap-2 text-[11px]">
        <Terminal className="h-3 w-3" />
        logs openfortivpn
        {q.data && (
          <span className="ml-auto text-[10px] text-[color:var(--color-cyber-muted)]">
            {q.data.lines.length} lignes{q.data.truncated && " (tronqué)"}
          </span>
        )}
        <button
          type="button"
          onClick={(e) => {
            e.preventDefault();
            q.refetch();
          }}
          className="text-[color:var(--color-cyber-muted)] hover:text-[color:var(--color-cyber-accent)]"
          title="Refresh now"
        >
          <RefreshCw
            className={cn("h-3 w-3", q.isFetching && "animate-spin")}
          />
        </button>
      </summary>
      <div className="mt-3">
        {q.isLoading && (
          <p className="text-[11px] text-[color:var(--color-cyber-muted)]">
            lecture…
          </p>
        )}
        {q.error && (
          <p className="cyber-chip cyber-chip-on block !rounded-none px-2 py-1 text-[10px]">
            {errorMessage(q.error)}
          </p>
        )}
        {q.data && q.data.lines.length === 0 && (
          <p className="text-[11px] italic text-[color:var(--color-cyber-dim)]">
            (aucun log — le tunnel n'a pas encore tourné depuis le boot)
          </p>
        )}
        {q.data && q.data.lines.length > 0 && (
          <pre className="max-h-96 overflow-auto border border-[color:var(--color-cyber-border)] bg-[color:var(--color-cyber-bg)] p-2 text-[10px] leading-relaxed font-mono text-[color:var(--color-cyber-muted)]">
            {q.data.lines.join("\n")}
          </pre>
        )}
      </div>
    </details>
  );
}

// ──────────────────────────── page ────────────────────────────────────

export default function FortinetConnect() {
  const configsQ = useQuery({
    queryKey: ["forti", "configs"],
    queryFn: listFortinetConfigs,
  });
  const statusQ = useQuery({
    queryKey: ["forti", "status"],
    queryFn: getFortinetStatus,
    refetchInterval: 5_000,
  });

  const isUp = statusQ.data?.state === "up";
  const activeConfig =
    isUp && statusQ.data?.slug
      ? configsQ.data?.find((c) => c.slug === statusQ.data?.slug)
      : undefined;

  return (
    <div className="mx-auto max-w-md px-4 py-6 sm:max-w-2xl sm:py-10">
      <header className="mb-6">
        <div className="cyber-label mb-2 flex items-center gap-2">
          <Lock className="cyber-glow h-3 w-3" />
          ssl vpn corporate · login
        </div>
        <div className="flex items-end justify-between gap-3">
          <h1
            className="cyber-display cyber-glitch text-3xl sm:text-4xl"
            data-text="FORTINET"
          >
            FORTINET
          </h1>
          <Link
            to="/vpn/fortinet"
            className="inline-flex items-center gap-1.5 border border-[color:var(--color-cyber-border-strong)] px-2 py-1.5 text-[10px] uppercase tracking-[0.15em] text-[color:var(--color-cyber-muted)] hover:border-[color:var(--color-cyber-accent)] hover:text-[color:var(--color-cyber-accent)]"
            title="Configuration des gateways"
          >
            <Settings className="h-3 w-3" />
            config
          </Link>
        </div>
        <p className="mt-2 text-[11px] uppercase tracking-[0.18em] text-[color:var(--color-cyber-muted)]">
          {isUp ? "tunnel actif" : "non connecté"}
        </p>
      </header>

      {(configsQ.isLoading || statusQ.isLoading) && (
        <p className="cyber-label cyber-cursor">loading…</p>
      )}
      {configsQ.error && (
        <p className="cyber-chip cyber-chip-on block !rounded-none px-3 py-2 text-xs">
          {errorMessage(configsQ.error)}
        </p>
      )}

      {configsQ.data && statusQ.data && (
        <div className="space-y-5">
          {isUp ? (
            <ConnectedPanel config={activeConfig} />
          ) : (
            <>
              {statusQ.data.state === "failed" && statusQ.data.last_error && (
                <div className="border border-[color:var(--color-cyber-accent)] bg-[color:var(--color-cyber-accent)]/8 p-3">
                  <div className="flex items-start gap-2">
                    <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[color:var(--color-cyber-accent)]" />
                    <p className="text-[11px] text-[color:var(--color-cyber-accent)]">
                      Dernière connexion échouée : {statusQ.data.last_error}
                    </p>
                  </div>
                </div>
              )}
              <LoginForm
                configs={configsQ.data}
                onLoggedIn={() => statusQ.refetch()}
              />
            </>
          )}

          <LogsViewer />
        </div>
      )}
    </div>
  );
}
